### ISSUE TITLE
How can I add custom Localization ?

### ISSUE THREAD

**Issue by fxcjahid** [Leshkens/laravel-read-time#1]
Hello,
I  would to add a custom language of French.
I have seen, There is already code for custom Local

```PHP
namespace App\Support\ReadTimeLocales;

use Leshkens\LaravelReadTime\Contracts\Localeable;
use function morphos\Russian\pluralize;

class Ru implements Localeable
{
    protected $unitMap = [
        'second' => 'секунда',
        'minute' => 'минута',
        'hour'   => 'час'
    ];

    public function result(int $number, string $unit): string
    {
        return pluralize($number, $this->unitMap[$unit]);
    }

}
```
But, This code I don't understand this properly, Can you help me more?

```code
--src
   ----Contracts
       ---CounterInterface.php
       ---LocaleInterface.php
   ----Facades
   ----Locales
       ---En.php
```

which folder do I need to add this code?

**Comment by Leshkens** [comment]
Hi. You never need to add or edit anything in the packages you install with Composer.

In this case, you have to create a localization file anywhere in your project for example: App\Support\ReadTimeLocales\Fr.php that implements the Localeable interface. 

Publish the config-file of the package: 
`php artisan vendor:publish --provider="Leshkens\LaravelReadTime\Providers\ReadTimeServiceProvider"`

And add your class in config/read-time.php in locales. For example:
```
'locales' => [
        'en' => Leshkens\LaravelReadTime\Locales\En::class,
        'fr' => App\Support\ReadTimeLocales\Fr::class
];
```

**Comment by fxcjahid** [comment]
Hello @Leshkens 
Can you check your code again, please?

I got this error : 

- https://prnt.sc/WIwjGx-dh0bh ( `Undefined type 'Leshkens\LaravelReadTime\Contracts\Localeable' `)
- https://prnt.sc/zJbQt0TdQzMd ( `Target class [App\Support\ReadTimeLocales\Fr] does not exist. `)

Folder Location :
```
resource
--- Lang
     ---ReadTimeLocales
          --- Fr.php
```

uses code:
```php
namespace App\Support\ReadTimeLocales;

use Illuminate\Support\Str;
use Leshkens\LaravelReadTime\Contracts\Localeable;

class Fr implements Localeable
{
	protected $unitMap = [
		'second' => 'seconde',
		'minute' => 'minute',
		'hour'   => 'heure'
	];

	public function result(int $number, string $unit): string
	{
		return Str::plural($number, $this->unitMap[$unit]);
	}
}
```

**Comment by Leshkens** [comment]
My mistake. It should be LocaleInterface, not Localable.
Example:
```
use Leshkens\LaravelReadTime\Contracts\LocaleInterface;

class Fr implements LocaleInterface
```

You have the wrong location. Laravel autoloads files from the App directory. Your directory would be `app\Support\ReadTimeLocales\Fr.php`

And you have an error in the order of the arguments for the plural method. You need: 
`Str::plural($this->unitMap[$unit], $number)` 
See example: https://github.com/Leshkens/laravel-read-time/blob/main/src/Locales/En.php#L25

**Comment by fxcjahid** [comment]
Thanks, @Leshkens 

I have solved this issues 

Following code: 
```php
class Fr implements LocaleInterface
{
	protected $unitMap = [
		'second' => 'seconde',
		'minute' => 'minute',
		'hour'   => 'heure'
	];

	public function result(int $number, string $unit): string
	{
		$unit = Str::plural($this->unitMap[$unit], $number);
		$text = sprintf('Lire dans %s %s', $number, $unit);
		return $text;
	}
}
```
